# Generated by Django 4.2.27 on 2026-01-30 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(help_text='Specific street or landmark', max_length=255)),
                ('city', models.CharField(default='Quezon City', max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('road_condition', models.CharField(blank=True, max_length=50)),
                ('traffic_volume', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor (Property Damage)'), ('INJURY', 'Injury'), ('FATAL', 'Fatal')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
